#!/usr/bin/env python
# -*- coding:utf8 -*-

# import os
# here = os.path.dirname(os.path.realpath(__file__))
# config_file = os.path.join(here, 'settings.py')
# app = create_app(config_file)

import wa

conf = {
    'sqlalchemyuri' : 'mysql://root:@127.0.0.1/wa_dev',
}

runable = wa.init(conf)

runable(
    host = '0.0.0.0',
    debug = True,
    reloader = True,
    )
