#!/usr/bin/env python
# -*- coding:utf8 -*-

import os

# from wa import create_app

# here = os.path.dirname(os.path.realpath(__file__))
# config_file = os.path.join(here, 'settings.py')
# app = create_app(config_file)

from wa.app import init

conf = {
    'sqlalchemyuri' : 'mysql://root:@127.0.0.1/wa_dev',
}

app = init(conf)

app.run(
    host = '0.0.0.0',
    debug = True,
    reloader = True,
    )
